version: "3.8"
networks:
  app:

services:

  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    networks:
      - app