# Generated by Django 4.0 on 2023-11-04 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hour_value', models.FloatField()),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('LUX', 'Lux')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('value', models.FloatField(blank=True, null=True)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('discount', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('consumable_item', models.ManyToManyField(blank=True, to='motel.ConsumableItem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accommodations', to='motel.room')),
            ],
        ),
    ]
