# Generated by Django 4.0 on 2024-01-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
